routes/admin.php
<?php

Route::get('/', ['as' => 'dashboard.index', 'uses' => 'DashboardController@index']);
Route::resource('post', 'PostController');
Route::resource('tag', 'TagController');
Route::resource('user', 'UserController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'HomeController@index')->name('home');
Route::get('/{postSlug}', 'HomeController@post')->name('post');

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('admin.dashboard.index');
    }
}

resources/views/admin/dashboard/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                <div class="col-sm-12 text-center">
                    <a href="{{ route('admin.user.index') }}" class="btn btn-success pull-right">Listado de Usuarios</a>
                    <a href="{{ route('admin.post.index') }}" class="btn btn-success pull-right">Listado de Posts</a>
                    <a href="{{ route('admin.tag.index') }}" class="btn btn-success pull-right">Listado de Tags</a>
                </div>
                </div>
            </div>
        </div>
        
    </div>
</div>
@endsection