routes/admin.php
<?php

Route::get('/', ['as' => 'dashboard.index', 'uses' => 'DashboardController@index']);
Route::resource('post', 'PostController');
Route::resource('tag', 'TagController');
Route::resource('user', 'UserController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'HomeController@index')->name('home');
Route::get('/{postSlug}', 'HomeController@post')->name('post');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Hash;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = Hash::make($password);
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Http\Requests\Admin\UserRequest;
use App\Http\Requests\Admin\UpdateUserRequest;
use Laracasts\Flash\Flash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('id','DESC')->get();
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
       $data = $request->all();

        $user = User::create([
                'name' => $data['name'],
                'email' => $data['email'],
                'password' => $data['password'],
            ]);

        if($user){
             Flash::success('Usuario Creado correctamente');
        }else{
            Flash::error('Fallo al crear el usuario');
        }

       // return redirect()->route('admin.user.index');
        return response()->json(array('status' => 'success','msg' => 'Elemento Enviado correctamente'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $user = User::find($user->id);

        return view('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(User $user, UpdateUserRequest $request)
    {
        
         /*if (empty($request->get('password'))) {
            $request->except('password');
            }*/
       $data = $request->all();

        $user = User::find($user->id);

        $user->fill($data);
        $user->save(); 

        if($user){
             Flash::success('Usuario Actualizado correctamente');
        }else{
            Flash::error('Fallo al actualizar el usuario');
        }
        
        //return redirect()->route('admin.user.index');
        return response()->json(array('status' => 'success','msg' => 'Elemento Actualizado correctamente'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $user = User::findOrFail($id);

        //if($user->id != Auth()->user->id){
         $user->delete();
          Flash::success('Usuario Eliminado correctamente');
      //}
       // return redirect()->route('admin.user.index');
      return response()->json(array('status' => 'success','msg' => 'Elemento Eliminado correctamente'));
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.app')
@section('content')
{!!Form::open(['route'=>'admin.user.store', 'method'=>'POST', 'data-toggle'=>'validator','role'=>'form','files' => true,'id'=>'form-new-item'])!!}
<section class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12">
			<div class="card">
				<div class="card-header">
					<h3 class="card-title"><a class="btn btn-default btn-xs" href="{{ route('admin.user.index') }}"><< Ver usuarios</a></h3>
					<div class="card-tools pull-right">
						{!!Form::submit('Crear',['class'=>'btn btn-block btn-primary btn-submit'])!!}
					</div>
				</div>
			</div>
		</div>
		<div class="col-sm-12 col-md-12">
			<div class="row">
				@include('admin.users.forms.index')
			</div>
		</div>
	</div>
</section>
{!!Form::close()!!}
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')
@section('content')
{!!Form::model($user,['route'=> ['admin.user.update',$user->id],'method'=>'PUT','files' => true, 'data-toggle'=>'validator','role'=>'form','id'=>'form-new-item'])!!}
<section class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12">
			<div class="card">
				<div class="card-header">
					<h3 class="card-title"><a class="btn btn-default btn-xs" href="{{ route('admin.user.index') }}"><< Ver usuarios</a></h3>
					<div class="card-tools pull-right">
						{!!Form::submit('Actualizar',['class'=>'btn btn-block btn-primary btn-update'])!!}
					</div>
				</div>
			</div>
		</div>
		<div class="col-sm-12 col-md-12">
			<div class="row">
				@include('admin.users.forms.index',['user' => $user])
			</div>
		</div>
	</div>
</section>
{!!Form::close()!!}
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('title')
Administración de Usuarios
@endsection

@section('content')
<section class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12">
			<div class="card">
				<div class="card-header">
					Listado de Usuarios
					<div class="card-tools pull-right">
					<a class="btn btn-success " href="{{ url('/admin') }}"><< Regresar al Administrador</a>
					<a class="btn btn-success pull-right" href="{{ route('admin.user.create') }}">Nuevo Usuario</a>
					</div>
				</div>
				<div class="card-body">
					<table class="table table-bordered table-hovered">
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Email</th>
						<th>Acciones</th>
					</tr>
					
				</thead>
				<tbody>
					@foreach($users as $user)
						<tr>
							<td>{{ $user->name }}</td>
							</td>
							<td>{{ $user->email }}</td>
							<td>
							        <a href="{{ route('admin.user.edit', $user->id) }}" class="btn btn-info">Editar</a>
							        <a href="{{ route('admin.user.destroy', $user->id) }}" class="btn btn-danger btn-delete">Eliminar</a>

							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
				</div>
			</div>
		
			
		</div>
	</div>
</section>

@endsection

resources/views/admin/users/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="text-center">

    </div>
@endsection