routes/admin.php
<?php

Route::get('/', ['as' => 'dashboard.index', 'uses' => 'DashboardController@index']);
Route::resource('post', 'PostController');
Route::resource('tag', 'TagController');
Route::resource('user', 'UserController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'HomeController@index')->name('home');
Route::get('/{postSlug}', 'HomeController@post')->name('post');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Carbon\Carbon;

class Post extends Model
{
    use Sluggable;

    protected $fillable = ['user_id','title','body','published_at'];

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    protected $dates = ['published_at'];


    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function tags()
	{
	    return $this->morphToMany(Tag::class,'taggable');
	}

    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', Carbon::now());
    }


    public function getTags()
    {
       
    }

    /**
     * Get the published_at attribute.
     *
     * @param  $date
     * @return string
     */
    public function getPublishedAtAttribute($date)
    {
        return Carbon::parse($date)->format('Y-m-d');
    }

    /**
     * @return string
     */
    public function getLinkAttribute()
    {
        return route('post', ['postSlug' => $this->slug]);
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Post;
use App\Tag;
use App\Http\Requests\Admin\PostRequest;
use Laracasts\Flash\Flash;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::orderBy('id','DESC')->get();
        //dd($posts[5]->tags);
        return view('admin.posts.index',compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::get()->pluck('name', 'id');
      return view('admin.posts.create',compact('tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        $data = $request->all();

        $post = Post::create([
                'title' => $data['title'],
                'body' => $data['body'],
                'published_at' => $data['published_at'],
                'user_id' => $data['user_id'],
            ]);

        
        if(is_array($data['tag']) && $data['tag'] != null){
            $post->tags()->attach($data['tag']);
            /*foreach ($data['tag'] as $tags) {
                $tag = Tag::find($tags);
                $post->tags()->save($tag);
            }*/  
        }
        

        if($post){
             Flash::success('Post Creado correctamente');
        }else{
            Flash::error('Fallo al crear el Post');
        }

       // return redirect()->route('admin.post.index');
        return response()->json(array('status' => 'success','msg' => 'Elemento Enviado correctamente'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
         $post = Post::find($post->id);
         $tags = Tag::get()->pluck('name', 'id');

        return view('admin.posts.edit', compact('post','tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
      public function update(Post $post, PostRequest $request)
    {
       $data = $request->all();

        $post = Post::find($post->id);

        $post->fill($data);
        $post->save(); 

        if(is_array($data['tag']) && $data['tag'] != null){
            $post->tags()->sync($data['tag']);
        }

        if($post){
             Flash::success('Post Actualizado correctamente');
        }else{
            Flash::error('Fallo al actualizar el Post');
        }
        
        //return redirect()->route('admin.post.index');
        return response()->json(array('status' => 'success','msg' => 'Elemento Actualizado correctamente'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $post = Post::findOrFail($id);
         $post->delete();
          Flash::success('Post Eliminado correctamente');
       // return redirect()->route('admin.post.index');
          return response()->json(array('status' => 'success','msg' => 'Elemento Eliminado correctamente'));
    }
}

resources/views/admin/posts/create.blade.php
@extends('layouts.app')
@section('content')
{!!Form::open(['route'=>'admin.post.store', 'method'=>'POST', 'data-toggle'=>'validator','role'=>'form','files' => true,'id'=>'form-new-item'])!!}
<section class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12">
			<div class="card">
				<div class="card-header">
					<h3 class="card-title"><a class="btn btn-default btn-xs" href="{{ route('admin.post.index') }}"><< Ver Posts</a></h3>
					<div class="card-tools pull-right">
						{!!Form::submit('Crear',['class'=>'btn btn-block btn-primary btn-submit'])!!}
					</div>
				</div>
			</div>
		</div>
		<div class="col-sm-12 col-md-12">
			<div class="row">
				@include('admin.posts.forms.index')
			</div>
		</div>
	</div>
</section>
{!!Form::close()!!}
@endsection

resources/views/admin/posts/edit.blade.php
@extends('layouts.app')
@section('content')
{!!Form::model($post,['route'=> ['admin.post.update',$post->id],'method'=>'PUT','files' => true, 'data-toggle'=>'validator','role'=>'form','id'=>'form-new-item'])!!}
<section class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12">
			<div class="card">
				<div class="card-header">
					<h3 class="card-title"><a class="btn btn-default btn-xs" href="{{ route('admin.post.index') }}"><< Ver Posts</a></h3>
					<div class="card-tools pull-right">
						{!!Form::submit('Actualizar',['class'=>'btn btn-block btn-primary btn-update'])!!}
					</div>
				</div>
			</div>
		</div>
		<div class="col-sm-12 col-md-12">
			<div class="row">
				@include('admin.posts.forms.index',['post' => $post,'tags'=>$tags])
			</div>
		</div>
	</div>
</section>
{!!Form::close()!!}
@endsection

resources/views/admin/posts/index.blade.php
@extends('layouts.app')

@section('title')
Administración de Posts
@endsection

@section('content')
<section class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12">
			<div class="card">
				<div class="card-header">
					Listado de Posts
					<div class="card-tools pull-right">
					<a class="btn btn-success " href="{{ url('/admin') }}"><< Regresar al Administrador</a>
					<a class="btn btn-success pull-right" href="{{ route('admin.post.create') }}">Nuevo Post</a>
					</div>
				</div>
				<div class="card-body">
					<table class="table table-bordered table-hovered">
				<thead>
					<tr>
						<th>Titulo</th>
						<th>Autor</th>
						<th>Tags</th>
						<th>Acciones</th>
					</tr>
					
				</thead>
				<tbody>
					@foreach($posts as $post)
						<tr>
							<td>{{ $post->title }}</td>
							</td>
							<td>{{ $post->user->name }}</td>

							<td>
								@if(count($post->tags) >=1)	
								@foreach($post->tags as $tag)	
									<span class="btn btn-sm btn-info">{{ $tag->name }}</span>
								@endforeach
								@endif
							</td>
							<td>
							        <a href="{{ route('admin.post.edit', $post->id) }}" class="btn btn-info">Editar</a>
							         <a href="{{ route('admin.post.destroy', $post->id) }}" class="btn btn-danger btn-delete">Eliminar</a>
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
				</div>
			</div>
		
			
		</div>
	</div>
</section>

@endsection

resources/views/admin/posts/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="text-center">

    </div>
@endsection