routes/admin.php
<?php

Route::get('/', ['as' => 'dashboard.index', 'uses' => 'DashboardController@index']);
Route::resource('post', 'PostController');
Route::resource('tag', 'TagController');
Route::resource('user', 'UserController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'HomeController@index')->name('home');
Route::get('/{postSlug}', 'HomeController@post')->name('post');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = [
        'name',
    ];

    /*public function taggable()
	{
	    return $this->morphTo();
	}*/

	public function posts()
    {
        return $this->morphedByMany(Post::class, 'taggable');
    }
 
}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Tag;
use App\Http\Requests\Admin\TagRequest;
use Laracasts\Flash\Flash;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $tags = Tag::orderBy('id','DESC')->get();
        return view('admin.tags.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $data = $request->all();

        $tag = Tag::create([
                'name' => $data['name']
            ]);

        if($tag){
             Flash::success('Tag Creada correctamente');
        }else{
            Flash::error('Fallo al crear la Tag');
        }

       // return redirect()->route('admin.tag.index');
        return response()->json(array('status' => 'success','msg' => 'Elemento Enviado correctamente'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        $tag = Tag::find($tag->id);

        return view('admin.tags.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Tag $tag, TagRequest $request)
    {

       $data = $request->all();

        $tag = Tag::find($tag->id);

        $tag->fill($data);
        $tag->save(); 

        if($tag){
             Flash::success('Tag Actualizada correctamente');
        }else{
            Flash::error('Fallo al actualizar la tag');
        }
        
        //return redirect()->route('admin.tag.index');
         return response()->json(array('status' => 'success','msg' => 'Elemento Actualizado correctamente'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tag = Tag::findOrFail($id);
         $tag->delete();
         Flash::success('Tag Eliminada correctamente');
         return response()->json(array('status' => 'success'));
       // return redirect()->route('admin.tag.index');
    }
}

resources/views/admin/tags/create.blade.php
@extends('layouts.app')
@section('content')
{!!Form::open(['route'=>'admin.tag.store', 'method'=>'POST', 'data-toggle'=>'validator','role'=>'form','files' => true,'id'=>'form-new-item'])!!}
<section class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12">
			<div class="card">
				<div class="card-header">
					<h3 class="card-title"><a class="btn btn-default btn-xs" href="{{ route('admin.tag.index') }}"><< Ver Tags</a></h3>
					<div class="card-tools pull-right">
						{!!Form::submit('Crear',['class'=>'btn btn-block btn-primary btn-submit'])!!}
					</div>
				</div>
			</div>
		</div>
		<div class="col-sm-12 col-md-12">
			<div class="row">
				@include('admin.tags.forms.index')
			</div>
		</div>
	</div>
</section>
{!!Form::close()!!}
@endsection

resources/views/admin/tags/edit.blade.php
@extends('layouts.app')
@section('content')
{!!Form::model($tag,['route'=> ['admin.tag.update',$tag->id],'method'=>'PUT','files' => true, 'data-toggle'=>'validator','role'=>'form','id'=>'form-new-item'])!!}
<section class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12">
			<div class="card">
				<div class="card-header">
					<h3 class="card-title"><a class="btn btn-default btn-xs" href="{{ route('admin.tag.index') }}"><< Ver Tags</a></h3>
					<div class="card-tools pull-right">
						{!!Form::submit('Actualizar',['class'=>'btn btn-block btn-primary btn-update'])!!}
					</div>
				</div>
			</div>
		</div>
		<div class="col-sm-12 col-md-12">
			<div class="row">
				@include('admin.tags.forms.index',['tag' => $tag])
			</div>
		</div>
	</div>
</section>
{!!Form::close()!!}
@endsection

resources/views/admin/tags/index.blade.php
@extends('layouts.app')

@section('title')
Administración de Tags
@endsection

@section('content')
<section class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12">
			<div class="card">
				<div class="card-header">
					Listado de Tags
					<div class="card-tools pull-right">
					<a class="btn btn-success " href="{{ url('/admin') }}"><< Regresar al Administrador</a>
					<a class="btn btn-success pull-right" href="{{ route('admin.tag.create') }}">Nuevo Tags</a>
					</div>
				</div>
				<div class="card-body">
					<table class="table table-bordered table-hovered">
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Acciones</th>
					</tr>
					
				</thead>
				<tbody>
					@foreach($tags as $tag)
						<tr>
							<td>{{ $tag->name }}</td>
							</td>
							<td>
							        <a href="{{ route('admin.tag.edit', $tag->id) }}" class="btn btn-info">Editar</a>
							         <a href="{{ route('admin.tag.destroy', $tag->id) }}" class="btn btn-danger btn-delete">Eliminar</a>
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
				</div>
			</div>
		
			
		</div>
	</div>
</section>

@endsection

resources/views/admin/tags/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="text-center">

    </div>
@endsection